### ISSUE TITLE
Ensure compatibility with PyQt4 v4.4 (and earlier) by keeping old-style signals and slots

### ISSUE THREAD

**Issue by PierreRaybaut** [PierreRaybaut/formlayout#35]
I have noticed that we progressively forgot to ensure compatibility with old-style signals and slots.

Unfortunately, that is not something we can test with travis because compatibility issues will cause silent fails (slots will not be triggered by emitted signals).

Here is what need to be fixed.
All occurences of the `QObject` method named `connect` need to be handled this way.
The following example:

``` python
self.widget.valueChanged.connect(layout.update)
```

should be replaced by:

``` python
if SIGNAL is None:
    self.widget.valueChanged.connect(layout.update)
else:
    self.connect(self.widget, SIGNAL("valueChanged(int)"), layout.update)
```

**Comment by fgallaire** [comment]
@PierreRaybaut Yes, I also noticed that.
But my question is: why is this needed ? I'm coding with Python 2.7/PyQt 4 and the new-style API works fine for me.

**Comment by PierreRaybaut** [comment]
@fgallaire Sometimes we don't have a choice. If a user has developed or is using a library based on PyQt API 1, he/she would be forced to use this old API. So, supporting old style signals and slots is useful in that case.

**Comment by fgallaire** [comment]
@PierreRaybaut It seems the 2 API can be used together without issue...

**Comment by PierreRaybaut** [comment]
@fgallaire Sorry for this confusion, I stopped coding regularly in 2012 and it's starting to play tricks on me. :)

Keeping old-style signals and slots support will provide compatibility with PyQt < 4.5.
Maybe we could drop for PyQt v4.4 (and earlier versions) because it is now really an old release.
What do you think about that?

**Comment by fgallaire** [comment]
Python 2.6: 10/2008
PyQt 4.5: 06/2009
Python 2.7: 07/210
We are in 2016, 7 years after the apparition of the new API. As we will release formlayout 2.0 as a 'new' formlayout: so many new features, API breaks and maybe a new name, we could drop PyQt4.4 support too. You really want to use it ? use formlayout 1.1.
It's good to be backward compatible, but clean code and easy dev are more important to me in this case.

**Comment by PierreRaybaut** [comment]
I totally agree with you on this: see Issue #41.
