### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by fgallaire** [PierreRaybaut/formlayout#39]
formlayout is licensed under the MIT license, but use PyQt which is GPL licensed.

However, the GPL is the most famous copylefted license, and is strongly viral.

So formlayout can't stay under MIT and should be released under the GPL.

PySide has been re-coded from scratch by Nokia (under LGPL) only to address this licensing issue.

**Comment by PierreRaybaut** [comment]
This license issue has already been debated in the past for Spyder or other projects using PyQt (or PySide) and the conclusion was that MIT license is acceptable for any library which is "only" depending on PyQt (there is no linking, no embedded PyQt source code, etc.).

The idea behind this is that, whatever the formlayout license may be, the end user developing and distributing an _application_ based on formlayout would be forced to comply with GPL (PyQt) or LGPL (PySide) terms anyway... Or, more importantly, the end-user must be free to choose a commercial license of PyQt to be able to distribute its own application based on PyQt and formlayout without having to comply with GPL license terms such as the obligation of distributing the complete source code of the application.

From a more "legal" point of view, PyQt GPL license has a `GPL_EXCEPTION.TXT` file which allows us explicitely to use an MIT license for distributing formlayout.

**Comment by fgallaire** [comment]
Thanks to teach me the existence of the PyQt `GPL_EXCEPTION.TXT`.
