### ISSUE TITLE
Python wiki link is broken

### ISSUE THREAD

**Issue by tim-seoss** [PierreRaybaut/formlayout#73]
The link from the Python wiki is broken (get's a 404 at https://code.google.com/archive/p/formlayout/ ) :

https://wiki.python.org/moin/GuiProgramming

I'd fix it, but I don't have a Python wiki account...

Cheers,

Tim.

**Comment by lesteve** [comment]
Thanks for letting us know. Full disclosure : I don't have a Python wiki account either. I guess the correct link should be:
http://pythonhosted.org/formlayout.

**Comment by PierreRaybaut** [comment]
Done
